### ISSUE TITLE
[Feature Request]: Close menu with E key (open/close inventory)

### ISSUE THREAD

**Issue by mnmt** [terrarium-earth/Cognition#1]
### Is your feature request related to a problem?

I am used to closing the menu of blocks (e.g. Furnace, chest, crafting table, modded machines, etc) in minecraft with the inventory key (for me, E). It is somewhat frustrating that this cannot be done with the experience obelisk.

### Solution(s)

When the obelisk's menu is open, pressing the inventory key closes the menu and returns control of the character back to the player.

### Describe alternatives you've considered

None.

### Mod Version

1.3.6

### Mod Loader Version

1.19.2 - 43.2.3

### Mod Loader

Forge

**Comment by cyanog3n** [comment]
Thanks for the suggestion! I've released a new update to fix it

**Comment by mnmt** [comment]
@cyanog3n Thank you! :D
