### ISSUE TITLE
Fluid names broken

### ISSUE THREAD

**Issue by kurtramone** [terrarium-earth/Cognition#10]
### Bug Description

Don't show fluid names
![fluid](https://github.com/terrarium-earth/Experience-Obelisk/assets/55619656/1ca078c0-1f54-47a2-a7a0-cc2e7623f74a)

Versions
MC 1.19.2
Mod 1.4.6
Forge 43.2.21

### How to Reproduce?

Search JEI

### Expected Behavior

Show names

### Version

1.4.6

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by cyanog3n** [comment]
resolved in 1.4.8. Thanks for the report!
