### ISSUE TITLE
Inventory close

### ISSUE THREAD

**Issue by kurtramone** [terrarium-earth/Cognition#11]
### Bug Description

From this:
https://github.com/terrarium-earth/Experience-Obelisk/issues/1

I can confirm it's not working
MC 1.19.2
Mod 1.4.6
Forge 43.2.21

It's hard coded to E or Esc key, I'm not using default key bind for inventory and E still works, but my configured key isn't

### How to Reproduce?

Enter Obelisk UI

### Expected Behavior

To work with your configured inventory key bind not just default one

### Version

1.4.6

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by cyanog3n** [comment]
resolved in 1.4.8. Thanks for the report!
