### ISSUE TITLE
[1.19.2 Bug]: Two types of fluid even though you can only get one

### ISSUE THREAD

**Issue by vizthex123** [terrarium-earth/Cognition#12]
### Bug Description

There's a bucket of Raw Experience (and fluid for it), but the obelisk cannot accept it nor can it be extracted.

### How to Reproduce?

1. Open minecraft
2. Filter JEI to the mod and check for the Raw Experience

### Expected Behavior

Only having Cognitium

### Version

1.4.8

### Mod Loader Version

43.3.2

### Mod Loader

Forge

### Logs or additional context

N/A - but it would be nice if you linked this issue tracker on the mod's page.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by vizthex123** [comment]
I also noticed that you can't pump fluids into the Obelisk (at least with Create's pump). It'd be nice if we could do that.

**Comment by cyanog3n** [comment]
Raw experience is a legacy fluid that was used in earlier versions of the mod; it's still around for backwards compatibility. It'll be removed when the content expansion releases!

Secondly, the obelisk receives fluid by exposing the default forge fluid capability. Fluid extraction and input has been tested with fluid pipes from mekanism, refined pipes and pipez, among others. I'm not sure how create does their pumps but I can't offer compatibility with every mod's fluid input/output system.
