### ISSUE TITLE
[Bug]: Experience Obelisk is accessable even when in a claimed chunk

### ISSUE THREAD

**Issue by Dalayeth** [terrarium-earth/Cognition#13]
### Bug Description

I'm playing on Direwolf20's 1.20 modpack version 1.1.0 
My experience obelisk is able to be accessed and XP can be added to or taken from it by other players even though it is in a claimed chunk.

### How to Reproduce?

1. Claim chunk in FTB menu
2. Place Experience Obelisk
3. Have another player right-click the block

### Expected Behavior

The block should not be accessible to other players when inside a claimed chunk.

### Version

1.4.8

### Mod Loader Version

Neoforge 47.1.76

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Aiidoneus** [comment]
I have this issue on my server as well. There is no event fired on the server when opening the GUI and does everything client-side. 
You can see more info here https://github.com/FTBTeam/FTB-Mods-Issues/issues/979#issuecomment-1772242670

**Comment by cyanog3n** [comment]
The experience obelisk now does the more normal thing and opens up a menu instead of working exclusively clientside. (ac8a5d5) Currently I'm testing it to make sure there are no unexpected issues.
