### ISSUE TITLE
[Bug]: Jade shows wrong fluid name

### ISSUE THREAD

**Issue by LiskoSlayer63** [terrarium-earth/Cognition#2]
### Bug Description

When looking Experience Obelisk block with Jade enabled, the inner tank shows as `fluid_type.unregistered_sadface`:

![nimetön](https://user-images.githubusercontent.com/10125529/217709852-916db240-e894-4e58-8c63-3c904ecb4292.png)

### How to Reproduce?

1. Install Experience Obelisk
2. Install Jade
3. Look at Experience Obelisk

### Expected Behavior

Jade to show `Raw Experience`

### Version

1.3.8

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

**Comment by IronHide4** [comment]
Also getting this in the Direwolf20 1.19 pack.  Jade is not installed

**Comment by LiskoSlayer63** [comment]
I actually cloned the repositroy and fixed it for me at least. I also limited it to 100 levels, but that's easy to revert.

**Comment by cyanog3n** [comment]
ty! bug is now fixed in update v1.4.0
