### ISSUE TITLE
[Bug]: Duplication of XP

### ISSUE THREAD

**Issue by zeziba** [terrarium-earth/Cognition#3]
### Bug Description

XP is duplicated if you collect the orb while in the GUI.

### How to Reproduce?

1. Place On ground
2. Open GUI to Obelisk
3. Collect any xp orb
4. Profit!

### Expected Behavior

Should not double dip xp.

### Version

1.3.8

### Mod Loader Version

1.19.2 43.2.6

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by cyanog3n** [comment]
Hi, I can't seem to replicate this issue. Could you provide a video demonstration of the bug if possible? Thank you!
