### ISSUE TITLE
[Feature Request]: configurable fluid XP

### ISSUE THREAD

**Issue by Saereth** [terrarium-earth/Cognition#4]
### Is your feature request related to a problem?

Modpacks often have 3-4 different types of fluid xp, some compatibility between types especially for the experience obelisk interactions would be very beneficial to creating a cohesive player experience. 

### Describe alternatives you've considered

Would you consider adding a config option to allow us to specify the type of experience the obelisk uses/creates internally OR a definable whitelist of fluids it will accept and autoconvert into rawExperience mos likely via the forge:experience fluid tag? This would be a huge help in packs with 3-4 different liquid xp types in unifying everything. 

### Mod Version

experienceobelisk-v1.3.8

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Additional context

Forge: 43.2.6

**Comment by TSM-EVO** [comment]
I agree with this suggestion, for reference, mods like Industrial Foregoing have Essence which doesn't natively import into the obelisk.

**Comment by cyanog3n** [comment]
Hi, thanks for the feedback! I'm working to implement cross-compatibility with other experience fluids in coming updates. Once the kinks have been ironed out the obelisk will be able to accept any fluid with the forge:experience tag.

**Comment by cyanog3n** [comment]
Thanks for the patience, This feature has been added as part of beta release v1.4.0 for both 1.18.2 and 1.19.2
