### ISSUE TITLE
[Bug]: Crash using Waystones

### ISSUE THREAD

**Issue by tgstyle** [terrarium-earth/Cognition#5]
### Bug Description

Client crashes when using a Waystone.

### How to Reproduce?

1. Multiplayer Server
2. Place 2 Waystones out of range of chunk load from eachother
3. Place Obelisk next to one Waystone
4. Empty all EXP in to an Obelisk
5. Take some out
6. May need to wait some time or walk away from Obelisk/Waystone chunk area
7. Use Waystone (may need to a few times)
8. Profit!

### Version

1.4.1

### Mod Loader Version

43.2.11

### Mod Loader

Forge

### Logs or additional context

https://gist.github.com/tgstyle/fed6642a4347768c29ef039bf8c649e0

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by tgstyle** [comment]
I have refined the above steps and can't always get it to reproduce but it does eventually crash using a waystone.

**Comment by Xplodin** [comment]
Just had a buddy crash to this exact issue.

**Comment by cyanog3n** [comment]
My bad, i think i know exactly what's causing this. Rolling out a fix soon
